### PR TITLE
Web support

### PR DESCRIPTION
**Pull request by danielroek**
Had to change the logic a bit to support web, as we do not get a `codePoint` like the currently supported keyboards. Made the `Stream` a char stream instead of `int`.

Found that giving the Widget a `bufferDuration` resulted in some missing inputs, but this was fixed by giving it a 200-500ms Duration. Not sure how you'd like to see this solved. Let me know if you want anything else of have any other feedback :)

### CODE REVIEW

**Comment by danielroek** [comment]
Tested it on Android with a Bluetooth keyboard, and everything seems to be working fine. Tested the issue with bufferDuration and it seems to be because I'm using a keyboard instead of a scanner to test it. This gives the input inconsistent times between the KeyEvents. 

I hope someone is able to give this PR a look in the near future, and test their usecases. I'm able to test this with an actual barcode scanner somewhere in the next two weeks, I'll keep this open until at least then.

**Comment by danielroek** [comment]
@shaxxx would you be able to publish the 0.1.1 version?

**Comment by shaxxx** [comment]
Hopefully, first thing in the morning.

**Comment by rshrc** [comment]
Is there any kind of OS dependency? I have Linux running flutter web and using the example app, I am unable to log anything. Is there something I am missing on?

**Comment by danielroek** [comment]
@rshrc You might need to increase the `bufferDuration`

**Comment by shaxxx** [comment]
I apologize for a delay, published 0.1.1 to pub.dev.
Thank you for your work.

**Pull request merged**
